<?php

namespace AG\AgenceimmoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
	public function getImgAccueil()
	{
		$qb=$this->createQueryBuilder('i');
		$qb->orWhere($qb->expr()->eq('i.url','?1'));
		$qb->orWhere($qb->expr()->eq('i.url','?2'));
		$qb->orWhere($qb->expr()->eq('i.url','?3'));
		$qb->orWhere($qb->expr()->eq('i.url','?4'));
		$qb->setParameter(1 , "19/new2.jpg");
		$qb->setParameter(2 , "19/new2-5.jpg");
		$qb->setParameter(3 , "20/new3.jpg");
		$qb->setParameter(4 , "20/new3-1.jpg");
		return $qb->getQuery()->getResult();
	}
}
