<?php

namespace AG\AgenceimmoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * type_immobilierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeimmobilierRepository extends EntityRepository
{
}
